campus_nnstu/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'', include('main.urls', namespace='main')),
    url(r'', include('articles.urls', namespace='articles')),
    url(r'', include('pages.urls', namespace='pages')),
    url(r'', include('vr.urls', namespace='vr')),
    url(r'', include('students.urls', namespace='students')),
    url(r'', include('events.urls', namespace='events')),
    url(r'', include('documents.urls', namespace='documents')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += [
        url(r'^uploads/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^student_council', views.student_council, name='student_council'),
    url(r'^leadership', views.leadership, name='leadership'),
    url(r'^dormitories', views.dormitories, name='dormitories'),
    url(r'^contact', views.contact, name='contact'),
    url(r'^newspaper', views.newspaper, name='newspaper'),
    url(r'^student_unification', views.student_unification, name='student_unification'),
]

pages/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'pages/(?P<pk>[0-9]+)/$', views.pages, name='pages'),
]

students/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'students/(?P<pk>[0-9]+)/$', views.main, name='main'),
    url(r'students/auth', views.auth, name='auth'),
    url(r'students/reg', views.reg, name='reg'),
    url(r'auth_students', views.auth_students, name='auth_students'),
    url(r'reg_mp_students', views.reg_mp_students, name='reg_mp_students'),
    url(r'reg_students', views.reg_students, name='reg_students'),
    url(r'students/logout', views.logout_students, name='logout_students'),
]

vr/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'answer/(?P<pk>[0-9]+)/$', views.answer_full, name='answer_full'),
    url(r'^new_issue', views.new_issue, name='new_issue'),
    url(r'^issues', views.issues, name='issues'),
    url(r'^answer', views.answer, name='answer'),
    url(r'^search', views.search, name='search'),
]

templates/include/css.html
{% load staticfiles %}

<!-- Favicon -->
<link rel="shortcut icon" type="image/x-icon" href="{% static 'campus_nnstu/images/favicon.png' %}">

<!-- All css files are included here. -->
<!-- Bootstrap fremwork main css -->
<link rel="stylesheet" href="{% static 'campus_nnstu/css/bootstrap.min.css' %}">
<!-- This core.css file contents all plugings css file. -->
<link rel="stylesheet" href="{% static 'campus_nnstu/css/core.css' %}">
<!-- Theme shortcodes/elements style -->
<link rel="stylesheet" href="{% static 'campus_nnstu/css/shortcode/shortcodes.css' %}">
<!-- Theme main style -->
<link rel="stylesheet" href="{% static 'campus_nnstu/css/style.css' %}">
<!-- Responsive css -->
<link rel="stylesheet" href="{% static 'campus_nnstu/css/responsive.css' %}">
<!-- Style customizer -->
<link rel="stylesheet" href="{% static 'campus_nnstu/css/color.css' %}">
<link rel="stylesheet" href="{% static 'campus_nnstu/css/lightbox.min.css' %}">

templates/include/footer.html
{% load staticfiles %}
<footer class="footer-area">
    <div class="footer-top ptb-110">
        <div class="container">
            <div class="row">
                <div class="col-md-5 col-sm-6">
                    <div class="footer-text footer-social">
                        <a href="{% url 'main:main' %}">
                            <img alt="" src="{% static 'campus_nnstu/images/logo/logo-2.png' %}">
                        </a>
                        <p>{{ settings.description_short_about }}</p>
                    </div>
                </div>
                <div class="col-md-3 col-sm-6">
                    <div class="footer-text mrg-sm3 mrg-xs">
                        <h3>Контакты</h3>
                        <ul class="footer-text-all">
                            <li><a href="{% url 'main:contact' %}">Контакты работников</a></li>
                            <li><a href="mailto:artgrosvil@gmail.com">Связаться с разработчиками</a></li>
                            <li><a href="{% url 'pages:pages' pk=8 %}">Карта портала</a></li>
                            <li><span style="color: #fff;">{{ settings.address|striptags }}</span></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-4 col-sm-6">
                    <div class="footer-text footer-social">
                        <h3>Мы в сетях</h3>
                        <ul>
                            <li><a href="{{ settings.link_vk }}" target="_blank"><i class="zmdi zmdi-vk"></i></a></li>
                            <li><a href="{{ settings.link_instagram }}" target="_blank"><i class="zmdi zmdi-instagram"></i></a></li>
                            <li><a href="{{ settings.link_youtube }}" target="_blank"><i class="icofont icofont-social-youtube"></i></a></li>
                        </ul>
                        <p><a href="{% url 'pages:pages' pk=10 %}">Политика</a> по обработке Персональных данных</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center">
                    <div class="footer-bottom-text ptb-20">
                        <p>Разработка 2017© <a href="{% url 'main:leadership' %}">Кандзюба Н.К</a> и <a href="http://artgrosvil.ru/" target="_blank">Трусов И.И.</a></p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

templates/include/js.html
{% load staticfiles %}
<!-- Modernizr JS -->
<script src="{% static 'campus_nnstu/js/vendor/modernizr-2.8.3.min.js' %}"></script>
<!-- jquery latest version -->
<script src="{% static 'campus_nnstu/js/vendor/jquery-1.12.0.min.js' %}"></script>
<!-- Bootstrap framework js -->
<script src="{% static 'campus_nnstu/js/bootstrap.min.js' %}"></script>
<!-- All js plugins included in this file. -->
<script src="{% static 'campus_nnstu/js/plugins/jquery-ui.min.js' %}"></script>
<script src="{% static 'campus_nnstu/js/plugins/headroom.min.js' %}"></script>
<script src="{% static 'campus_nnstu/js/plugins/jquery.countdown.min.js' %}"></script>
<script src="{% static 'campus_nnstu/js/plugins/jquery.counterup.min.js' %}"></script>
<script src="{% static 'campus_nnstu/js/plugins/jquery.meanmenu.min.js' %}"></script>
<script src="{% static 'campus_nnstu/js/plugins/jquery.waypoints.min.js' %}"></script>
<script src="{% static 'campus_nnstu/js/plugins/slick.min.js' %}"></script>
<script src="{% static 'campus_nnstu/js/main.js' %}"></script>
<script src="{% static 'campus_nnstu/js/custom.js' %}"></script>
<script src="{% static 'campus_nnstu/js/lightbox.min.js' %}"></script>
<script id="dsq-count-scr" src="//campus-ngtu-ru.disqus.com/count.js" async></script>

templates/include/nav.html
{% load staticfiles %}
<!-- Start of header area -->
<header class="header-area">
    <div class="header-top blue-bg">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-sm-7 col-xs-12">
                    <div class="header-top-info">
                        <ul>
                            <li>
                                <a href="http://www.nntu.ru/" target="_blank"><img src="{% static 'campus_nnstu/images/logo/nnstu_logo.png' %}" style="width: 35px;"></a>
                            </li>
                            <li>
                                <a href="#" style="cursor: default;">
                                    <i class="zmdi zmdi-phone"></i>
                                </a>
                                {{ settings.phone }}
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-6 col-sm-5 hidden-xs">
                    <div class="header-top-right">
                        <div class="header-top-social f-right">
                            <p class="link_n"><a href="http://studgorod.nntu.ru" target="_blank">АИС Студгородок</a></p>
                            <p style="border-left: 1px solid #fff; padding-left: 10px;">Следите за нами :</p>
                            <ul>
                                <li><a href="{{ settings.link_vk }}" target="_blank"><i class="icofont icofont-social-vk"></i></a></li>
                                <li><a href="{{ settings.link_instagram }}" target="_blank"><i class="icofont icofont-social-instagram"></i></a></li>
                                <li><a href="{{ settings.link_youtube }}" target="_blank"><i class="icofont icofont-social-youtube"></i></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header-bottom stick-h2">
        <div class="container">
            <div class="row">
                <div class="col-md-2 col-sm-12 col-xs-12">
                    <div class="logo">
                        <a href="{% url 'main:main' %}"><img src="{% static 'campus_nnstu/images/logo/logo.png' %}" alt=""></a>
                    </div>
                </div>
                <div class="col-md-10 hidden-sm hidden-xs">
                    <div class="menu-area f-right">
                        <nav>
                            <ul id="header_navigation">
                                <li><a href="{% url 'articles:main' %}">Новости</a></li>
                                <li><a href="{% url 'events:main' %}">Мероприятия</a></li>
                                <li class="coloumn-one"><a class="none-padding" href="#">О студгородке <i class="fa fa-caret-down" aria-hidden="true"></i></a>
                                    <ul class="nav-submenu">
                                        <li><a href="{% url 'main:dormitories' %}">Общежития</a></li>
{#                                        <li><a href="{% url 'main:leadership' %}">Подразделения</a></li>#}
                                        <li><a href="{% url 'documents:main' %}">Документы</a></li>
                                        <li><a href="{% url 'main:contact' %}">Контакты</a></li>
                                    </ul>
                                </li>
                                <li class="coloumn-one"><a class="none-padding" href="#">Заселение <i class="fa fa-caret-down" aria-hidden="true"></i></a>
                                    <ul class="nav-submenu">
                                        {% for page in pages %}
                                            <li><a href="{% url 'pages:pages' pk=page.pk %}">{{ page.title }}</a></li>
                                        {% endfor %}
                                        {% for page in pages_student_unification %}
                                            <li><a href="{% url 'pages:pages' pk=page.pk %}">{{ page.title }}</a></li>
                                        {% endfor %}
                                    </ul>
                                </li>

                                {% if settings.enable_vr %}
                                    <li class="coloumn-one"><a class="none-padding" href="#">Виртуальная приемная <i class="fa fa-caret-down" aria-hidden="true"></i></a>
                                        <ul class="nav-submenu">
                                            <li><a href="{% url 'vr:issues' %}">Задать вопрос</a></li>
                                            <li><a href="{% url 'vr:answer' %}">Ответы на обращения</a></li>
                                        </ul>
                                    </li>
                                {% endif %}

                                <li class="coloumn-one"><a class="none-padding" href="#">Внеучебная работа <i class="fa fa-caret-down" aria-hidden="true"></i></a>
                                    <ul class="nav-submenu">
                                        <li><a href="{% url 'main:student_council' %}">Студсовет студгородка</a></li>
                                        <li><a href="{% url 'main:newspaper' %}">Журнал "Пропуск"</a></li>
                                        <li><a href="{% url 'main:student_unification' %}">Студенческие объединения НГТУ</a></li>
                                    </ul>
                                </li>

                                {% if settings.enable_students %}
                                    {% if request.session.logged %}
                                        <li class="coloumn-one"><a class="none-padding" href="#">// Профиль <i class="fa fa-caret-down" aria-hidden="true"></i></a>
                                            <ul>
                                                <li><a href="{% url 'students:main' pk=request.session.id %}">Мой профиль</a></li>
                                                <li><a href="{% url 'students:logout_students' %}">Выйти</a></li>
                                            </ul>
                                        </li>
                                    {% else %}
                                        <li class="coloumn-one"><a class="none-padding" href="#">// Войти <i class="fa fa-caret-down" aria-hidden="true"></i></a>
                                            <ul>
                                                <li><a href="{% url 'students:reg' %}">Регистрация</a></li>
                                                <li><a href="{% url 'students:auth' %}">Авторизация</a></li>
                                            </ul>
                                        </li>
                                    {% endif %}
                                {% endif %}
                            </ul>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- mobile-menu-area start -->
<div class="mobile-menu-area">
    <div class="container">
        <div class="row">
            <div class="hidden-lg hidden-md col-sm-12 col-xs-12">
                <div class="mobile-menu">
                    <nav id="dropdown">
                        <ul>
                            <li><a href="{% url 'articles:main' %}">Новости</a></li>
                            <li><a href="{% url 'events:main' %}">Мероприятия</a></li>
                            <li><a href="#">О студгородке<i class="fa fa-caret-down" aria-hidden="true"></i></a>
                                <ul>
                                    <li><a href="{% url 'main:dormitories' %}">Общежития</a></li>
{#                                    <li><a href="{% url 'main:leadership' %}">Подразделения</a></li>#}
                                    <li><a href="{% url 'documents:main' %}">Документы</a></li>
                                    <li><a href="{% url 'main:contact' %}">Контакты</a></li>
                                </ul>
                            </li>

                            <li><a href="#">Заселение <i class="fa fa-caret-down" aria-hidden="true"></i></a>
                                <ul>
                                    {% for page in pages %}
                                        <li><a href="{% url 'pages:pages' pk=page.pk %}">{{ page.title }}</a></li>
                                    {% endfor %}
                                    {% for page in pages_student_unification %}
                                        <li><a href="{% url 'pages:pages' pk=page.pk %}">{{ page.title }}</a></li>
                                    {% endfor %}
                                </ul>
                            </li>

                            {% if settings.enable_vr %}
                                <li><a href="#">Виртуальная приемная<i class="fa fa-caret-down" aria-hidden="true"></i></a>
                                    <ul>
                                        <li><a href="{% url 'vr:issues' %}">Задать вопрос</a></li>
                                        <li><a href="{% url 'vr:answer' %}">Ответы на вопросы</a></li>
                                    </ul>
                                </li>
                            {% endif %}

                            <li><a href="#">Внеучебная работа<i class="fa fa-caret-down" aria-hidden="true"></i></a>
                                <ul>
                                    <li><a href="{% url 'main:student_council' %}">Студсовет студгородка</a></li>
                                    <li><a href="{% url 'main:newspaper' %}">Журнал "Пропуск"</a></li>
                                    <li><a href="{% url 'main:student_unification' %}">Студенческие объединения НГТУ</a></li>
                                </ul>
                            </li>

                            {% if settings.enable_students %}
                                {% if request.session.logged %}
                                    <li><a href="#">Профиль<i class="fa fa-caret-down" aria-hidden="true"></i></a>
                                        <ul>
                                            <li><a href="{% url 'students:main' pk=request.session.id %}">Мой профиль</a></li>
                                            <li><a href="{% url 'students:logout_students' %}">Выйти</a></li>
                                        </ul>
                                    </li>
                                {% else %}
                                    <li><a href="#">Войти<i class="fa fa-caret-down" aria-hidden="true"></i></a>
                                        <ul>
                                            <li><a href="{% url 'students:reg' %}">Регистрация</a></li>
                                            <li><a href="{% url 'students:auth' %}">Авторизация</a></li>
                                        </ul>
                                    </li>
                                {% endif %}
                            {% endif %}
                        </ul>
                    </nav>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- mobile-menu-area end -->