articles/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'articles/(?P<pk>[0-9]+)/$', views.full, name='full'),
    url(r'articles', views.main, name='main'),
]

campus_nnstu/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'', include('main.urls', namespace='main')),
    url(r'', include('articles.urls', namespace='articles')),
    url(r'', include('pages.urls', namespace='pages')),
    url(r'', include('vr.urls', namespace='vr')),
    url(r'', include('students.urls', namespace='students')),
    url(r'', include('events.urls', namespace='events')),
    url(r'', include('documents.urls', namespace='documents')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += [
        url(r'^uploads/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^student_council', views.student_council, name='student_council'),
    url(r'^leadership', views.leadership, name='leadership'),
    url(r'^dormitories', views.dormitories, name='dormitories'),
    url(r'^contact', views.contact, name='contact'),
    url(r'^newspaper', views.newspaper, name='newspaper'),
    url(r'^student_unification', views.student_unification, name='student_unification'),
]

vr/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'answer/(?P<pk>[0-9]+)/$', views.answer_full, name='answer_full'),
    url(r'^new_issue', views.new_issue, name='new_issue'),
    url(r'^issues', views.issues, name='issues'),
    url(r'^answer', views.answer, name='answer'),
    url(r'^search', views.search, name='search'),
]

articles/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class Articles(models.Model):
    author = models.ForeignKey('auth.User', verbose_name='Автор')
    title = models.CharField(verbose_name='Заголовок', max_length=150, default='')
    text = RichTextField(verbose_name='Текст статьи')
    created_date = models.DateTimeField(verbose_name='Дата публикации', default=timezone.now)
    img = models.FileField(verbose_name='Картинка')
    img_thumbnail_short = ImageSpecField(source='img', processors=[ResizeToFill(380, 350)], format='JPEG', options={'quality': 100})
    img_thumbnail_full = ImageSpecField(source='img', processors=[ResizeToFill(774, 380)], format='JPEG', options={'quality': 100})
    comments_status = models.BooleanField(verbose_name='Отображать комментарии', default=False)

    class Meta:
        verbose_name = 'Статьи и Новости'
        verbose_name_plural = 'Статьи и Новости'

    def __str__(self):
        return self.title

main/models.py
from django.db import models
from ckeditor.fields import RichTextField
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill


class Slider(models.Model):
    title = models.CharField(verbose_name='Заголовок слайдера', max_length=300, default='')
    description = models.CharField(verbose_name='Текст на слайде', max_length=500, default='')
    button_text = models.CharField(verbose_name='Текст на кнопке', max_length=100, default='')
    button_link = models.CharField(verbose_name='Ссылка на кнпоке (Напрмер: contact, без домена сайта)', max_length=200, default='')
    img = models.FileField(verbose_name='Фотография')
    photo_thumbnail = ImageSpecField(source='img', processors=[ResizeToFill(1920, 753)], format='JPEG', options={'quality': 100})

    class Meta:
        verbose_name = 'Слайдер'
        verbose_name_plural = 'Слайдер'

    def __str__(self):
        return self.description


class Employees(models.Model):
    name = models.CharField(verbose_name='Имя', max_length=100, default='')
    post = models.CharField(verbose_name='Должность', max_length=100, blank=True)
    description = RichTextField(verbose_name='Описание обязанностей', max_length=3000, default='')
    address = models.CharField(verbose_name='Адрес', max_length=400, default='')
    email = models.EmailField(verbose_name='Email(можно не заполнять)', max_length=100, blank=True)
    vk = models.CharField(verbose_name='Ссылка на VK(можно не заполнять)', max_length=100, blank=True)
    phone = models.CharField(verbose_name='Телефон', max_length=20, blank=True)
    photo = models.FileField(verbose_name='Фото')
    photo_thumbnail = ImageSpecField(source='photo', processors=[ResizeToFill(270, 340)], format='JPEG', options={'quality': 100})
    show_main_page_status = models.BooleanField(verbose_name='Вывести на главную страницу', default=False)
    time_work = RichTextField(verbose_name='Приемные часы', max_length=300, blank=True)
    leadership_status = models.BooleanField(verbose_name='Руководство', default=False)
    student_unification_status = models.BooleanField(verbose_name='Студенческие объединения', default=False)

    class Meta:
        verbose_name = 'Сотрудники'
        verbose_name_plural = 'Сотрудники'

    def __str__(self):
        return self.name


class Newspaper(models.Model):
    title = models.CharField(verbose_name='Название(выпуск)', max_length=300)
    images = models.FileField(verbose_name='Картика')
    images_thumbnail = ImageSpecField(source='images', processors=[ResizeToFill(270, 340)], format='JPEG', options={'quality': 100})
    file = models.FileField(verbose_name='Файл', max_length=300)

    class Meta:
        verbose_name = 'Газета'
        verbose_name_plural = 'Газета'

    def __str__(self):
        return self.title


class StudentCouncil(models.Model):
    group = models.CharField(verbose_name='Группа', max_length=300)
    description = RichTextField(verbose_name='Описание')
    employees = models.ManyToManyField(Employees, verbose_name='Работники')

    class Meta:
        verbose_name = 'Страница: Студсовет студгородка'
        verbose_name_plural = 'Страница: Студсовет студгородка'

    def __str__(self):
        return self.group


class Leadership(models.Model):
    group = models.CharField(verbose_name='Группа', max_length=300)
    employees = models.ManyToManyField(Employees, verbose_name='Работники')

    class Meta:
        verbose_name = 'Страница: Руководство'
        verbose_name_plural = 'Страница: Руководство'

    def __str__(self):
        return self.group


class Contact(models.Model):
    location = models.CharField(verbose_name='Координаты карты', max_length=150)
    email_form = models.EmailField(verbose_name='Email формы обратной связи', max_length=100)
    address = RichTextField(verbose_name='Адрес', max_length=200)
    phone = RichTextField(verbose_name='Телефон', max_length=100)
    email = models.CharField(verbose_name='Email на страницу', max_length=100, default='')
    contact_leadership = RichTextField(verbose_name='Руководство', default='')
    contact_ssg = RichTextField(verbose_name='ССГ', default='')

    class Meta:
        verbose_name = 'Контакты'
        verbose_name_plural = 'Контакты'

articles/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from main.views import get_context_data
from .models import Articles
from settings.models import Settings

def main(request):
    # загрузка обязательных данных
    context_data = get_context_data(request)

    settings = Settings.objects.all().first()

    articles = Articles.objects.all().order_by('-created_date')
    paginator = Paginator(articles, settings.count_articles)
    page = request.GET.get('page')
    try:
        articles = paginator.page(page)
    except PageNotAnInteger:
        articles = paginator.page(1)
    except EmptyPage:
        articles = paginator.page(paginator.num_pages)

    # вывод данных в отображении
    context_data.update({'articles': articles})
    return render(request, 'articles/main.html', context_data)


def full(request, pk):
    # загрузка обязательных данных
    context_data = get_context_data(request)

    article = get_object_or_404(Articles, pk=pk)

    # вывод данных в отображении
    context_data.update({'article': article})
    return render(request, 'articles/full.html', context_data)

main/views.py
from django.shortcuts import render

from .models import Slider, Employees, Contact, Leadership, StudentCouncil, Newspaper
from articles.models import Articles
from students.models import Students
from settings.models import Settings
from vr.models import Issues
from pages.models import Pages
from events.models import Events
from dormitories.models import Dormitories


# получение повторяющихся данных в отображении
def get_context_data(request):
    # обязательные данные
    settings = Settings.objects.first()
    pages = Pages.objects.all().filter(show_status=True, show_student_unification=False)
    pages_student_unification = Pages.objects.all().filter(show_status=True, show_student_unification=True)

    context_data = {'settings': settings, 'pages': pages, 'pages_student_unification':pages_student_unification}
    return context_data


def main(request):
    # загрузка обязательных данных
    context_data = get_context_data(request)

    employees = Employees.objects.filter(show_main_page_status=True, student_unification_status=False)
    articles = Articles.objects.all().order_by('-created_date')[:3]
    events = Events.objects.all().order_by('-date')[:4]
    slider = Slider.objects.all()

    employees_count = Employees.objects.count()
    students_count = Students.objects.count()
    events_count = Events.objects.count()
    issues_count = Issues.objects.count()
    hh = {'employees_count': employees_count, 'students_count': students_count, 'events_count': events_count, 'issues_count': issues_count}

    # вывод данных в отображении
    context_data.update({'events': events, 'articles': articles, 'employees': employees, 'hh': hh, 'slider': slider})
    return render(request, 'main/main.html', context_data)


def student_council(request):
    # загрузка обязательных данных
    context_data = get_context_data(request)

    student_council = StudentCouncil.objects.all()
    student_council_dormitories = Dormitories.objects.all().order_by('id')

    # вывод данных в отображении
    context_data.update({'student_council': student_council, 'student_council_dormitories': student_council_dormitories})
    return render(request, 'main/student_council.html', context_data)


def leadership(request):
    # загрузка обязательных данных
    context_data = get_context_data(request)

    leadership = Leadership.objects.all()

    # вывод данных в отображении
    context_data.update({'leadership': leadership})
    return render(request, 'main/leadership.html', context_data)


def dormitories(request):
    # загрузка обязательных данных
    context_data = get_context_data(request)

    dormitories = Dormitories.objects.all().order_by('id')

    # вывод данных в отображении
    context_data.update({'dormitories': dormitories})
    return render(request, 'dormitories/main.html', context_data)


def contact(request):
    # загрузка обязательных данных
    context_data = get_context_data(request)

    contact = Contact.objects.first()

    # вывод данных в отображении
    context_data.update({'contact': contact})
    return render(request, 'main/contact.html', context_data)


def newspaper(request):
    # загрузка обязательных данных
    context_data = get_context_data(request)

    newspaper = Newspaper.objects.all().order_by('-id')

    # вывод данных в отображении
    context_data.update({'newspaper': newspaper})
    return render(request, 'main/newspaper.html', context_data)


def student_unification(request):
    # загрузка обязательных данных
    context_data = get_context_data(request)

    employees = Employees.objects.filter(student_unification_status=True)

    # вывод данных в отображении
    context_data.update({'employees': employees})
    return render(request, 'main/student_unification.html', context_data)

templates/articles/full.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{ article.title }} | {{ settings.title }}</title>
    <meta name="description" content="{{ settings.description }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% include "include/css.html" %}
</head>

<body>
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your
    experience.</p>
<![endif]-->
<!-- Body main wrapper start -->
<div class="wrapper">
    <!-- Start of header area -->
    {% include "include/nav.html" %}
    <!-- mobile-menu-area end -->
    <!-- End of header area -->
    <section class="breadcrumbs-area gray-bg ptb-110 page-title-fix solid">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breadcrumbs breadcrumbst1">
                        <h2 class="page-title">{{ article.title }}</h2>
                        <ul>
                            <li><a class="active" href="{% url 'main:main' %}">Главная </a></li>
                            <li><a href="{% url 'articles:main' %}">Новости студгородка</a></li>
                            <li>{{ article.title }}</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Start page content -->
    <section class="news-details-area pt-110">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="news-details-all gray-bg">
                        <img src="{{ article.img_thumbnail_full.url }}" alt="">
                        <div class="news-details-all-area pt-40 pl-200 pr-200">
                            <div class="news-details-top">
                                <h2>{{ article.title }}</h2>
                                <div class="news-details-calender">
                                    <div class="blog-meta-2">
                                        <span class="published3">
                                            <i class="icofont icofont-ui-calendar"></i>
                                            {{ article.created_date|date:"M d, Y" }}
                                        </span>
                                    </div>
                                </div>
                            </div>
                            <div class="news-details-middle">
                                <p>{{ article.text|safe }}</p>
                            </div>
                            {% if article.comments_status == True %}
                                <div class="leave-comment pt-60">
                                    <h3 class="leave-comment-text">Комментарии:</h3>
                                    <div id="disqus_thread"></div>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End page content -->
    <!-- Start footer area -->
    {% include "include/footer.html" %}
    <!-- End footer area -->
    <!-- start scrollUp
    ============================================ -->
    <div id="toTop">
        <i class="fa fa-chevron-up"></i>
    </div>
</div>
{% include "include/js.html" %}
<script>
    (function () { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://campus-ngtu-ru.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
</body>
</html>

templates/articles/main.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Новости студгородка | {{ settings.title }}</title>
    <meta name="description" content="{{ settings.description }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% include "include/css.html" %}
</head>

<body>
<!--[if lt IE 8]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
    <![endif]-->
<!-- Body main wrapper start -->
<div class="wrapper">
    <!-- Start of header area -->
    {% include "include/nav.html" %}
    <!-- mobile-menu-area end -->
    <!-- End of header area -->
    <section class="breadcrumbs-area gray-bg ptb-110 page-title-fix solid">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breadcrumbs breadcrumbst1">
                        <h2 class="page-title">Новости студгородка</h2>
                        <ul>
                            <li><a class="active" href="{% url 'main:main' %}">Главная </a></li>
                            <li>Новости студгородка</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Start page content -->
    <section class="news-page-area ptb-110">
        <div class="container">
            <div class="row">
                {% for post in articles %}
                    <div class="col-md-4 col-sm-6">
                        <div class="news-are">
                            <a href="{% url 'articles:full' pk=post.pk %}">
                                <div class="news-img">
                                    <img src="{{ post.img_thumbnail_short.url }}" alt="">
                                    <div class="news-date">
                                        <div class="blog-meta-2">
                                        <span class="published3">
                                            <i class="icofont icofont-ui-calendar"></i>
                                            {{ post.created_date|date:"M d, Y" }}
                                        </span>
                                        </div>
                                    </div>
                                </div>
                                <div class="img-text gray-bg" style="min-height: 220px;">
                                    <h4>{{ post.title|truncatechars:50 }}</h4>
                                    <p>{{ post.text|striptags|truncatechars:100|safe }}</p>
                                </div>
                            </a>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="row">
                <div class="col-md-12 text-center pt-20">
                    <div class="pages2">
                        <ul>
                            {% if articles.has_previous %}
                                <li><a href="?page={{ articles.previous_page_number }}">←</a></li>
                            {% endif %}
                            {% for num in articles.paginator.page_range %}
                                {% if num == articles.number %}
                                    <li class="active"><a href="#">{{ num }}</a></li>
                                {% else %}
                                    <li><a href="?page={{ num }}">{{ num }}</a></li>
                                {% endif %}
                            {% endfor %}
                            {% if news.has_next %}
                                <li><a href="?page={{ articles.next_page_number }}">→</a></li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End page content -->
    <!-- Start footer area -->
    {% include "include/footer.html" %}
    <!-- End footer area -->
    <!-- start scrollUp -->
    <div id="toTop">
        <i class="fa fa-chevron-up"></i>
    </div>
</div>
{% include "include/js.html" %}
</body>
</html>