campus_nnstu/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),
    url(r'', include('main.urls', namespace='main')),
    url(r'', include('articles.urls', namespace='articles')),
    url(r'', include('pages.urls', namespace='pages')),
    url(r'', include('vr.urls', namespace='vr')),
    url(r'', include('students.urls', namespace='students')),
    url(r'', include('events.urls', namespace='events')),
    url(r'', include('documents.urls', namespace='documents')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

if settings.DEBUG:
    urlpatterns += [
        url(r'^uploads/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    ]

main/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
    url(r'^student_council', views.student_council, name='student_council'),
    url(r'^leadership', views.leadership, name='leadership'),
    url(r'^dormitories', views.dormitories, name='dormitories'),
    url(r'^contact', views.contact, name='contact'),
    url(r'^newspaper', views.newspaper, name='newspaper'),
    url(r'^student_unification', views.student_unification, name='student_unification'),
]

vr/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'answer/(?P<pk>[0-9]+)/$', views.answer_full, name='answer_full'),
    url(r'^new_issue', views.new_issue, name='new_issue'),
    url(r'^issues', views.issues, name='issues'),
    url(r'^answer', views.answer, name='answer'),
    url(r'^search', views.search, name='search'),
]

vr/models.py
from django.db import models
from django.utils import timezone
from ckeditor.fields import RichTextField


class Issues(models.Model):
    employees = models.ForeignKey('main.Employees', verbose_name='Сотрудник', default='')
    name = models.CharField(verbose_name='ФИО', max_length=100, default='')
    email = models.EmailField(verbose_name='Email', max_length=100, default='')
    phone = models.CharField(verbose_name='Телефон', max_length=30, default='')
    who = models.CharField(verbose_name='Кто по отношению к НГТУ', max_length=100, default='')
    who_sub = models.CharField(verbose_name='Рубрика', max_length=300, default='')
    subject = models.CharField(verbose_name='Тема', max_length=200, default='')
    question = models.TextField(verbose_name='Вопрос', max_length=500, default='')
    answer = RichTextField(verbose_name='Ответ', max_length=2000)
    publication = models.BooleanField(verbose_name='Публикация вопроса', default=False)
    date = models.DateField(verbose_name='Дата вопроса', default=timezone.now)
    date_answer = models.DateField(verbose_name='Дата ответа', default=timezone.now)
    comments = models.BooleanField(verbose_name='Разрешить обсуждение вопроса', default=False)

    class Meta:
        verbose_name = 'Вопросы'
        verbose_name_plural = 'Вопросы'

    def __str__(self):
        return self.subject

vr/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404
from django.core.exceptions import ObjectDoesNotExist

from main.views import get_context_data
from .models import Issues
from main.models import Employees
import json


def issues(request):
    # обязательные данные
    context_data = get_context_data(request)

    employees = Employees.objects.filter(leadership_status=True, student_unification_status=False)

    # вывод данных в отображении
    context_data.update({'employees': employees})
    return render(request, 'vr/issues.html', context_data)


def answer(request):
    # обязательные данные
    context_data = get_context_data(request)

    issues = Issues.objects.all().filter(publication=True)

    # вывод данных в отображении
    context_data.update({'issues': issues})
    return render(request, 'vr/answer.html', context_data)


def answer_full(request, pk):
    # обязательные данные
    context_data = get_context_data(request)

    issue = get_object_or_404(Issues, pk=pk)

    # вывод данных в отображении
    context_data.update({'issue': issue})
    return render(request, 'vr/answer_full.html', context_data)


def new_issue(request):
    if request.POST and request.is_ajax:
        employees_id = request.POST.get('employees')
        name = request.POST.get('name')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        who = request.POST.get('who')
        who_sub = request.POST.get('who_sub')
        subject = request.POST.get('subject')
        question = request.POST.get('question')

        try:
            employees = Employees.objects.get(id=employees_id)
            Issues.objects.create(employees=employees, name=name, email=email, phone=phone, who=who, subject=subject, question=question, who_sub=who_sub)
            data_response = {'status': 'success'}
        except ObjectDoesNotExist:
            data_response = {'status': 'fail'}
        return HttpResponse(json.dumps(data_response))


def search(request):
    # обязательные данные
    context_data = get_context_data(request)

    if request.POST:
        issue = request.POST.get('issue')

        issues = Issues.objects.filter(question__contains=issue)

        # вывод данных в отображении
        context_data.update({'issues': issues})
        return render(request, 'vr/answer.html', context_data)

templates/vr/answer.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Ответы на вопросы | {{ settings.title }}</title>
    <meta name="description" content="{{ settings.description }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% include "include/css.html" %}
</head>

<body>
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your
    experience.</p>
<![endif]-->
<!-- Body main wrapper start -->
<div class="wrapper">
    <!-- Start of header area -->
    {% include "include/nav.html" %}
    <!-- mobile-menu-area end -->
    <!-- End of header area -->
    <section class="breadcrumbs-area gray-bg ptb-110 page-title-fix solid">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breadcrumbs breadcrumbst1">
                        <h2 class="page-title">Ответы на вопросы</h2>
                        <ul>
                            <li><a class="active" href="{% url 'main:main' %}">Главная </a></li>
                            <li><a class="active" href="{% url 'main:main' %}">Виртуальная примемная</a></li>
                            <li>Ответы на вопросы</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Start page content -->
    <section class="news-page-area ptb-110">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-md-offset-6">
                    <form action="{% url 'vr:search' %}" method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <input style="height: 30px;" type="text" name="issue" class="form-control" placeholder="Поиск по существующим вопросам">
                            <span class="input-group-btn">
                                <button class="btn btn-default" type="submit">Найти</button>
                            </span>
                        </div>
                    </form>
                </div>
            </div>
            <div class="row">
                <div class="conract-area-bottom">
                    <table class="table table-striped">
                        <thead>
                        <tr>
                            <th>От кого</th>
                            <th>Тема</th>
                            <th>Кому вопрос</th>
                            <th>Дата вопроса</th>
                            <th>Дата ответа</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for qq in issues %}
                            <tr>
                                <td>{{ qq.name }}</td>
                                <td><a href="{% url 'vr:answer_full' pk=qq.pk %}">{{ qq.question }}</a></td>
                                <td>{{ qq.employees }}</td>
                                <td>{{ qq.date }}</td>
                                <td>{{ qq.date_answer }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
    <!-- End page content -->
    <!-- Start footer area -->
    {% include "include/footer.html" %}
    <!-- End footer area -->
    <!-- start scrollUp
    ============================================ -->
    <div id="toTop">
        <i class="fa fa-chevron-up"></i>
    </div>
</div>
{% include "include/js.html" %}
</body>
</html>

templates/vr/answer_full.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{{ issue.question }} | {{ settings.title }}</title>
    <meta name="description" content="{{ settings.description }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% include "include/css.html" %}
</head>

<body>
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your
    experience.</p>
<![endif]-->
<!-- Body main wrapper start -->
<div class="wrapper">
    <!-- Start of header area -->
    {% include "include/nav.html" %}
    <!-- mobile-menu-area end -->
    <!-- End of header area -->
    <section class="breadcrumbs-area gray-bg ptb-110 page-title-fix solid">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breadcrumbs breadcrumbst1">
                        <h2 class="page-title">Ответ на вопрос</h2>
                        <ul>
                            <li><a class="active" href="{% url 'main:main' %}">Главная </a></li>
                            <li><a class="active" href="{% url 'main:main' %}">Виртуальная примемная</a></li>
                            <li>Ответ на вопрос</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Start page content -->
    <section class="news-page-area ptb-110">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-sm-12">
                    <div class="events-details-right-sidebar">
                        <div class="about-lectures">
                            <h3>Тема</h3>
                            <p>{{ issue.subject }}</p>
                        </div>
                        <div class="about-lectures pt-40">
                            <h3>Вопрос</h3>
                            <p>{{ issue.question }}</p>
                        </div>
                        <div class="about-lectures pt-40">
                            <h3>Ответ</h3>
                            <p>{{ issue.answer|safe }}</p>
                        </div>
                        {% if issue.comments == True %}
                            <div class="about-lectures pt-40">
                                <h3>Комментарии</h3>
                                <div id="disqus_thread"></div>
                            </div>
                        {% endif %}
                    </div>
                </div>
                <div class="col-md-4 col-sm-12">
                    <div class="events-details-sidebar" style="margin-top: 0px;">
                        <h3>Данные по вопросу</h3>
                        <div class="events-details-book">
                            <ul>
                                <li><a href="#">Кто задал вопрос<span>{{ issue.who }}</span></a></li>
                                <li><a href="#">Имя<span>{{ issue.name }}</span></a></li>
                                <li><a href="#">Кому обращение<span>{{ issue.employees.post }}</span></a></li>
                                <li><a href="#">Имя<span>{{ issue.employees.name }}</span></a></li>
                                <li><a href="#">Дата вопроса<span>{{ issue.date }}</span></a></li>
                                <li><a href="#">Дата ответа<span>{{ issue.date_answer }}</span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End page content -->
    <!-- Start footer area -->
    {% include "include/footer.html" %}
    <!-- End footer area -->
    <!-- start scrollUp
    ============================================ -->
    <div id="toTop">
        <i class="fa fa-chevron-up"></i>
    </div>
</div>
{% include "include/js.html" %}
<script>
    (function () { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://campus-ngtu-ru.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
</body>
</html>

templates/vr/issues.html
{% load staticfiles %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>Задать вопрос | {{ settings.title }}</title>
    <meta name="description" content="{{ settings.description }}">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    {% include "include/css.html" %}
</head>

<body>
<!--[if lt IE 8]>
<p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your
    experience.</p>
<![endif]-->
<!-- Body main wrapper start -->
<div class="wrapper">
    <!-- Start of header area -->
    {% include "include/nav.html" %}
    <!-- mobile-menu-area end -->
    <!-- End of header area -->
    <section class="breadcrumbs-area gray-bg ptb-110 page-title-fix solid">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="breadcrumbs breadcrumbst1">
                        <h2 class="page-title">Задать вопрос</h2>
                        <ul>
                            <li><a class="active" href="{% url 'main:main' %}">Главная</a></li>
                            <li><a class="active" href="{% url 'main:main' %}">Виртуальная примемная</a></li>
                            <li>Задать вопрос</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Start page content -->
    <section class="news-page-area ptb-110">
        <div class="container">
            <div class="row">
                <p>Уважаемый гость портала студгородка НГТУ им. Р.Е. Алексеева! На данной странице Вы можете оставить обращение на любую тему по вопросам заселения,
                    проживания в общежитиях, воспитательного процесса в студгородке, сообщить о проблеме как бытового, так и межличностного характера и т.д</p>
                <details>
                    <summary style="font-weight: 700">Правила использования виртуальной приемной</summary>
                    {{ settings.rules_vr|safe }}
                </details>
                <div class="conract-area-bottom">
                    <form id="issues-form" action="{% url 'vr:new_issue' %}" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 pt-20">
                                <div class="main-input">
                                    <i class="icofont icofont-graduate-alt"></i>
                                    <select name="employees">
                                        <option value="" disabled selected>Должностное лицо</option>
                                        {% for employee in employees %}
                                            <option value="{{ employee.id }}">{{ employee.name }} ({{ employee.post }})</option>
                                        {% endfor %}
                                    </select>
                                    <small id="employees" class="form-text text-muted">Выберите должностное лицо, которому хотите отправить обращение</small>
                                </div>
                            </div>
                            <div class="col-md-6 pt-20">
                                <div class="main-input">
                                    <input name="name" placeholder="Ваши фамилия, имя и отчество" type="text">
                                    <i class="icofont icofont-user"></i>
                                    <small id="name" class="form-text text-muted">Укажите Ваши данные, анонимные обращения не рассматриваются</small>
                                </div>
                            </div>
                            <div class="col-md-6 pt-20">
                                <div class="main-input">
                                    <input name="email" placeholder="Ваш email" type="email">
                                    <i class="icofont icofont-email"></i>
                                    <small id="email" class="form-text text-muted">На данную почту Вы получите уведомления по обращению</small>
                                </div>
                            </div>
                            <div class="col-md-6 pt-20">
                                <div class="main-input">
                                    <input name="phone" placeholder="Контактный телефон" type="text">
                                    <i class="icofont icofont-phone"></i>
                                    <small id="phone" class="form-text text-muted">Укажите Ваш контактный номер телефона для уточнения информации по обращению</small>
                                </div>
                            </div>
                            <div class="col-md-6 pt-20">
                                <div class="main-input">
                                    <i class="icofont icofont-book-alt"></i>
                                    <select name="who">
                                        <option value="" disabled selected>По отношению к НГТУ Вы являетесь</option>
                                        <option value="Не имею отношения к НГТУ">Не имею отношения к НГТУ</option>
                                        <option value="Абитуриент">Абитуриент</option>
                                        <option value="Студент">Студент</option>
                                        <option value="Слушатель">Слушатель</option>
                                        <option value="Аспирант">Аспирант</option>
                                        <option value="Преподаватель">Преподаватель</option>
                                        <option value="Сотрудник">Сотрудник</option>
                                        <option value="Выпускник">Выпускник</option>
                                    </select>
                                    <small id="who" class="form-text text-muted">Выберите Ваш статус по отношению к НГТУ им. Р. Е. Алексеева</small>
                                </div>
                            </div>
                            <div class="col-md-6 pt-20">
                                <div class="main-input">
                                    <i class="icofont icofont-book-alt"></i>
                                    <select name="who_sub">
                                        <option value="" disabled selected>Рубрика</option>
                                        <option value="Заселение">Заселение</option>
                                        <option value="Переселение">Переселение</option>
                                        <option value="Выселение">Выселение</option>
                                        <option value="Вахта">Вахта</option>
                                        <option value="Клининг">Клининг</option>
                                        <option value="Старостат">Старостат</option>
                                        <option value="Электрика">Электрика</option>
                                        <option value="Сантехника">Сантехника</option>
                                        <option value="Состояние комнаты/блока">Состояние комнаты/блока</option>
                                        <option value="Работа заведующих/комендантов">Работа заведующих/комендантов</option>
                                        <option value="Нарушения Правил внутреннего распорядка">Нарушения Правил внутреннего распорядка</option>
                                        <option value="Конфликтная ситуация; Места общего пользования">Конфликтная ситуация; Места общего пользования</option>
                                        <option value="Другое">Другое</option>
                                    </select>
                                    <small id="who" class="form-text text-muted">Выберите тему вопроса</small>
                                </div>
                            </div>
                            <div class="col-md-12 pt-20">
                                <div class="main-input">
                                    <input name="subject" placeholder="Тема вопроса" type="text">
                                    <i class="icofont icofont-pencil"></i>
                                    <small id="subject" class="form-text text-muted">Укажите тему обращения</small>
                                </div>
                            </div>
                            <div class="col-md-12 pt-20">
                                <div class="text-leave2">
                                    <textarea name="question" placeholder="Опишите Ваш вопрос как можно более подробно. Это уменьшит время его обработки."></textarea>
                                    <input id="checkBox" type="checkbox" required style="height:auto;width: 3%;">
                                    <label for="checkBox">Я согласен(на) с правилами использования Виртуальной Приёмной студгородка НГТУ им. Р.Е. Алексеева.</label>
                                </div>
                            </div>
                            <div class="col-md-12 pt-20">
                                <div class="text-leave2">
                                    <button class="submit">Отправить вопрос</button>
                                </div>
                            </div>
                        </div>
                        <p id="issues-form-message"></p>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- End page content -->
    <!-- Start footer area -->
    {% include "include/footer.html" %}
    <!-- End footer area -->
    <!-- start scrollUp
    ============================================ -->
    <div id="toTop">
        <i class="fa fa-chevron-up"></i>
    </div>
</div>
{% include "include/js.html" %}
</body>
</html>